### ISSUE TITLE
Is there plans to continue?

### ISSUE THREAD

**Issue by Elderwolf1700** [jkunczik/home-assistant-omada#16]
I'm looking at running this on my HA but noticed it's running an older version that is missing features that I use in the newer version. Just curious if this is planned to be updated or not.

**Comment by mclever** [comment]
@DraTrav  @jkunczik can you please update the version of the beta add-on

**Comment by Zanadar** [comment]
Appears this add on is no longer maintained... it is many versions behind mbentleys docker image on which it is based

**Comment by jkunczik** [comment]
Hi @Elderwolf1700, @mclever and @Zanadar,
I am pretty busy right now, which is why I am not finding the time to attend to this issue. It is in my backlog and I will get to it as soon as possible. I just don't know when that will be. However, everyone with a bit of knowledge about Docker files could update both versions. If someone has the time, I will gladly accept a pull request and test the update!

**Comment by lieven121** [comment]
Hi @jkunczik  I created a pr for upgrading beta
If ok and aproved i will also do the same for the stable?
see #18

**Comment by lieven121** [comment]
@jkunczik  Just to be sure the last stable beta was 5.9
but if you look at the OMADA_URL it was https://static.tp-link.com/upload/beta/2023/202310/20231027/Omada_SDN_Controller_v5.13.10_Linux_x64.tar.gz(Beta).gz
Which is a BETA/Early Access release

Would the stable be 5.9, 5.13 or the following stable release?

**Comment by jkunczik** [comment]
Thank you @lieven121 for providing the PR. I hope it is working as expected for everybody. If someone finds problems, please let me know.
