### ISSUE TITLE
Upgrading from stable to beta

### ISSUE THREAD

**Issue by robbo1001** [jkunczik/home-assistant-omada#17]
Hi there. 

Thanks for the great work on this integration. I have been using the stable version for a while, but am keen to try the features of the later version of the software controller. What is the process for upgrading from Stable, to Beta? If I install the beta, does it overwrite the stable, or do they both run together (and the stable will need to be disabled)?

Also, will my settings automatically be carried across from stable to beta, or do I need to use the backup/restore function?

Many thanks

**Comment by jkunczik** [comment]
Hi robbo1001,

The two versions are completely separate. To move from Stable to Beta, do the following:

1. Download your current config in Omada
2. Install the Beta Add-On
3. Stop the Stable Add-On (disable start at boot-up)
4. Start the Beta Add-On
5. Perform the initial set-up (It does not matter what you enter here, because it will get overwritten with your backup)
6. Restore your backup.

**Comment by robbo1001** [comment]
Nice one. Thanks
