### ISSUE TITLE
Restructure the repository to increase maintanability

### ISSUE THREAD

**Issue by jkunczik** [jkunczik/home-assistant-omada#43]
Due to its nature, the repo has not much in common with mbentley/docker-omada-controller anymore. This way we can provide a Stable and a Beta image. However, this also makes maintaining the repo (getting upstream updates) a pain and error prone. Hence, I detachted this repo from upstream and plan on including subrepos, which are directly forked from upstream and have only minimal (the necessary) changes applied to them. Through this approach, I am hoping to make pulling upstream changes way easier.

**Comment by mclever** [comment]
figured since I needed to migrate to another controller I would take the time to change from beta to stable and am unable to install stable at the moment. guessing you know, just wanted to make sure you saw this though

Failed to install add-on
Can't install dratrav/home-assistant-omada-stable:5.14.7: 404 Client Error for http+docker://localhost/v1.47/images/create?tag=5.14.7&fromImage=dratrav%2Fhome-assistant-omada-stable&platform=linux%2Famd64: Not Found ("manifest for dratrav/home-assistant-omada-stable:5.14.7 not found: manifest unknown: manifest unknown")
